name: Quete
description: The best place for yout to find the best job..


version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.2
  flutter_svg: ^0.19.2+1
  splashscreen: ^1.2.0
  avatar_glow: ^1.1.0
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.10.0
  bottom_navy_bar: ^5.6.0
  smooth_star_rating: 1.1.1
  table_calendar: ^2.3.3
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.0+1"

#    cloud_firestore: "^0.16.0"
#    cloud_functions: "^0.9.0"
#    firebase_storage: "^7.0.0"
#    firebase_messaging: "^8.0.0-dev.14"



  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Igreen"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/introduction/
    - assets/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Futura Book
       fonts:
         - asset: fonts/Futura Book font.ttf
     - family: Futura Extra Black
       fonts:
             - asset: fonts/Futura Extra Black font.ttf
     - family: Futura Heavy
       fonts:
             - asset: fonts/Futura Heavy font.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
