name: Quete
description: The best place for yout to find the best job..


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.2
  flutter_svg: ^0.19.2+1
  splashscreen: ^1.2.0
  avatar_glow: ^1.1.0
  provider: ^4.3.3
  google_fonts: any
  flutter_screenutil: any
  font_awesome_flutter: ^8.10.0
  bottom_navy_bar: ^5.6.0
  table_calendar: ^2.3.3
  graphql: "4.0.1"
  http: "0.12.2"
  form_field_validator: ^1.0.1
  uuid: ^2.2.2
  stream_transform: ^1.2.0
  #firebase
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.0+1"
  cloud_firestore: "^0.16.0"
  #    cloud_functions: "^0.9.0"
  #    firebase_storage: "^7.0.0"
  #    firebase_messaging: "^8.0.0-dev.14"
  # location
  flutter_google_places: ^0.2.6
  google_maps_webservice:
  google_maps_flutter: ^1.2.0
  geolocator:
  geocoding: ^1.0.5
  flutter_polyline_points: ^0.2.4
  cupertino_icons: ^1.0.0
  # artemis build runner
  artemis: '>=6.0.0 <7.0.0' # only if you're using ArtemisClient!
  json_annotation: ^3.1.0
  equatable: ^1.2.5
  meta: '>=1.0.0 <2.0.0' # only if you have non nullable fields
  gql: '>=0.12.3 <1.0.0'




dev_dependencies:

  artemis: '>=6.0.0 <7.0.0'
  build_runner: ^1.10.4
  json_serializable: ^3.5.0
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Igreen"


flutter:
  uses-material-design: true

  assets:
    - assets/images/introduction/
    - assets/images/Schedule/
    - assets/icons/
    - assets/utils/

  fonts:
     - family: Futura Book
       fonts:
         - asset: fonts/Futura Book font.ttf
     - family: Futura Extra Black
       fonts:
             - asset: fonts/Futura Extra Black font.ttf
     - family: Futura Heavy
       fonts:
             - asset: fonts/Futura Heavy font.ttf


